services:
  postgres:
    image: postgres:17
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"     
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
